DROP EXTENSION IF EXISTS "uuid-ossp";

DROP TABLE IF EXISTS song_book_image;

DROP TABLE IF EXISTS image;

DROP TABLE IF EXISTS song_book_song;

DROP TABLE IF EXISTS official_song_book;

DROP TABLE IF EXISTS song_book;

DROP TABLE song_tag;

DROP TABLE tag;

DROP TABLE IF EXISTS song;

DROP TABLE IF EXISTS melody;

DROP TABLE IF EXISTS user_owner;

DROP TABLE IF EXISTS owner;

DROP TABLE IF EXISTS songbook_user;
